Update index.md
ioos/bio_mobilization_workshop pull request #113
Opened 2024-03-11 21:55 UTC by timvdstap

Minor updates to the General Information page

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

You may delete these instructions from your comment.

\- Marine Biological Data Mobilization Workshop Maintainers
</details>

2024-03-12 12:52 UTC, MathewBiddle commented
These changes look good. We just need to discuss the dates in here. I prefer the website says we end on the 23 with optional 24 discussed during the workshop.

2024-03-15 18:56 UTC, MathewBiddle requested changes
@timvdstap do you mind reverting back a few of these changes. I really like your emphasis and text additions here.

2024-03-15 18:56 UTC, MathewBiddle commented on index.md
> +humandate: "April 22-24, 2024"    # human-readable dates for the workshop (e.g., "Feb 17-18, 2020")
@timvdstap do you mind reverting this back?

2024-03-15 18:56 UTC, MathewBiddle commented on index.md
> +enddate: 2023-04-24        # machine-readable end date for the workshop in YYYY-MM-DD format like 2015-01-02
this too

2024-03-15 18:56 UTC, MathewBiddle commented on index.md
> +This workshop is intended to be a small hands-on, interactive virtual workshop focused on mobilizing marine biodiversity observation datasets to the <a href="https://obis.org/">Ocean Biodiversity Inf
this too

2024-03-15 18:56 UTC, MathewBiddle commented on index.md
> +The videos created for the Marine Biodiversity Data Mobilization Workshop can be found in [this playlist](https://youtube.com/playlist?list=PLlgUwSvpCFS7zytaWbZ6f4Szm3PnpFj_J).
Adjust to Biological

2024-04-08 00:51 UTC, jdpye commented
my read is that this is still waiting on @timvdstap to twiddle the dates back ? if not, it's mergeable.

2024-04-08 15:42 UTC, timvdstap commented on index.md
> +humandate: "April 22-24, 2024"    # human-readable dates for the workshop (e.g., "Feb 17-18, 2020")
Sorry not sure how this slipped under the radara - resolved now back to April 23.

2024-04-08 16:34 UTC, MathewBiddle approved these changes

2024-04-08 16:35 UTC, merged